name: Update imageParameters.json and sitemap.xml

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Update imageParameters.json
        env:
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }}
          NEXT_PUBLIC_CLOUDINARY_API_SECRET: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_SECRET }}
        run: npm run update-imageParameters

      - name: Update sitemap.xml
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        run: npm run update-sitemap

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/imageParameters.json public/sitemap.xml
          git commit -m "🤖 Auto-update imageParameters.json and sitemap.xml [skip ci]" || echo "No changes to commit"
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: update-files

    steps:
      - name: Trigger Netlify build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
